[package]
name = "adar-registry"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "Adar registry is a collection of containers for managing resources in dynamically loaded extensions/plugins."
repository = "https://github.com/nandee95/adar/tree/main/adar_registry"
keywords = ["extension", "plugin", "event", "observer", "dynamic"]
documentation = "https://docs.rs/adar-registry"
